### PR TITLE
Size Check Script added

### PR DESCRIPTION
**Pull request by sbSteveK**
Testing size check for CI

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by TingDaoK** [comment]
`.builder/actions/__pycache__/crt_size_check.cpython-39.pyc` this seems like should not be included?

**Review by bretambrose — COMMENTED** [review]
Should this be checking the overall dist size as well?

**Comment by graebm** [comment]
> `.builder/actions/__pycache__/crt_size_check.cpython-39.pyc` this seems like should not be included?

Yeah, you'll want to put `*.pyc` in your [global git ignore](https://stackoverflow.com/a/7335487)

**Review by bretambrose — APPROVED** [review]

**Comment by TingDaoK** [comment]
> Should this be checking the overall dist size as well?

Maybe not? We only include the compiled binaries in the npm package, and that's what the check for. It's not meaningful to check the size of `lib/` and `include/`

**Pull request merged**
